"""add tags to task

Revision ID: 69e1979b684e
Revises: 461a668f211a
Create Date: 2026-08-10 23:03:40.981848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69e1979b684e'
down_revision: Union[str, Sequence[str], None] = '461a668f211a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'tags')
    # ### end Alembic commands ###
