"""add user table and task owner_id_2

Revision ID: cb3cd394559d
Revises: da5bfafcc168
Create Date: 2026-08-11 18:00:42.362663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3cd394559d'
down_revision: Union[str, Sequence[str], None] = 'da5bfafcc168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_task_owner_id'), 'task', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'task', 'user', ['owner_id'], ['id'])
    op.drop_column('task', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('tags', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_owner_id'), table_name='task')
    op.drop_column('task', 'owner_id')
    # ### end Alembic commands ###
